use_plugins: &use_plugins
    plugins:
      - automattic/bash-cache#v1.0.0: ~
      - automattic/git-s3-cache#add/vm-host-support:
          bucket: "a8c-repo-mirrors"
          repo: "wordpress-mobile/wordpress-ios/"

xcode_version: &xcode_version
  IMAGE_ID: xcode-12.5.1

env: &env
  # If you'll need more than one key-value, update to:
  #
  # env:
  #   <<: *xcode_version
  #   other_key: other_value
  env: *xcode_version

# This is the default pipeline – it will build and test the app
steps:
  #################
  # Build the app
  #################
  - label: ":pipeline: Build"
    key: "build"
    command: ".buildkite/commands/build-for-testing.sh"
    <<: *env
    <<: *use_plugins

  #################
  # Run Unit Tests
  #################
  - label: "🧪 Unit Tests"
    command: |
      echo "--- 📦 Downloading Build Artifacts"
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar
      echo "--- 🧪 Testing"
      bundle install
      bundle exec fastlane test_without_building name:WordPressUnitTests try_count:3
    depends_on: "build"
    <<: *env
    <<: *use_plugins

  #################
  # Lint Translations
  #################
  - label: "🧹 Lint Translations"
    command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
    agents:
      queue: "default"

  #################
  # UI Tests
  #################
  - label: "🧪 UI Tests (iPhone)"
    command: |
      echo "--- 📦 Downloading Build Artifacts"
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar

      echo "--- :wrench: Fixing VM"
      brew install openjdk@11
      sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

      echo "--- :rubygems: Setting up Gems"
      bundle install

      echo "--- :cocoapods: Setting up Pods"
      bundle exec pod install

      echo "--- 🧪 Testing"
      rake mocks &
      bundle exec fastlane test_without_building name:WordPressUITests try_count:3 device:"iPhone 11" ios-version:"14.1"
    depends_on: "build"
    <<: *env
    <<: *use_plugins

  - label: "🧪 UI Tests (iPad)"
    command: |
      echo "--- 📦 Downloading Build Artifacts"
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar

      echo "--- :wrench: Fixing VM"
      brew install openjdk@11
      sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

      echo "--- :rubygems: Setting up Gems"
      bundle install

      echo "--- :cocoapods: Setting up Pods"
      bundle exec pod install

      echo "--- 🧪 Testing"
      rake mocks &
      bundle exec fastlane test_without_building name:WordPressUITests try_count:3 device:"iPad Air (4th generation)" ios-version:"14.1"
    depends_on: "build"
    <<: *env
    <<: *use_plugins
