x_use_plugins: &use_plugins
    plugins:
      - automattic/bash-cache#v1.0.0: ~
      - automattic/git-s3-cache#add/vm-host-support:
          bucket: "a8c-repo-mirrors"
          repo: "wordpress-mobile/wordpress-ios/"

# Common environment values for the `env` key.
#
# To add more, simply add another entry at the same indentation as `IMAGE_ID`.
#
# Usage in a step with only these values:
#
#   env: *common_env
#
# Usage in a step with other values:
#
#   env:
#     <<: *common_env
#     other_key: "other value"
x_common_env: &common_env
  IMAGE_ID: xcode-12.5.1

# This is the default pipeline – it will build and test the app
steps:
  #################
  # Build the app
  #################
  - label: ":pipeline: Build"
    key: "build"
    command: ".buildkite/commands/build-for-testing.sh"
    env: *common_env
    <<: *use_plugins

  #################
  # Run Unit Tests
  #################
  - label: "🧪 Unit Tests"
    command: |
      echo "--- 📦 Downloading Build Artifacts"
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar
      echo "--- 🧪 Testing"
      bundle install
      bundle exec fastlane test_without_building name:WordPressUnitTests try_count:3
    depends_on: "build"
    env: *common_env
    <<: *use_plugins

  #################
  # Lint Translations
  #################
  - label: "🧹 Lint Translations"
    command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
    agents:
      queue: "default"

  #################
  # UI Tests
  #################
  - label: "🧪 UI Tests (iPhone)"
    command: |
      echo "--- 📦 Downloading Build Artifacts"
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar

      echo "--- :wrench: Fixing VM"
      brew install openjdk@11
      sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

      echo "--- :rubygems: Setting up Gems"
      bundle install

      echo "--- :cocoapods: Setting up Pods"
      bundle exec pod install

      echo "--- 🧪 Testing"
      rake mocks &
      bundle exec fastlane test_without_building name:WordPressUITests try_count:3 device:"iPhone 11" ios-version:"14.1"
    depends_on: "build"
    env: *common_env
    <<: *use_plugins

  - label: "🧪 UI Tests (iPad)"
    command: |
      echo "--- 📦 Downloading Build Artifacts"
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar

      echo "--- :wrench: Fixing VM"
      brew install openjdk@11
      sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

      echo "--- :rubygems: Setting up Gems"
      bundle install

      echo "--- :cocoapods: Setting up Pods"
      bundle exec pod install

      echo "--- 🧪 Testing"
      rake mocks &
      bundle exec fastlane test_without_building name:WordPressUITests try_count:3 device:"iPad Air (4th generation)" ios-version:"14.1"
    depends_on: "build"
    env: *common_env
    <<: *use_plugins
